<script setup>
import { computed, onMounted, ref } from 'vue'
import { adminApi } from '@/api/admin.js'

const loading = ref(true)
const error = ref('')
const period = ref('30d')
const analytics = ref({ works: {}, labs: {}, summary: {}, series: [], referrals: [], topContent: [], devices: [], locations: [], visitors: [], isps: [], recent: [] })
const count = (group, key) => analytics.value[group]?.[key] || 0
const maxVisits = computed(() => Math.max(...(analytics.value.series || []).map((point) => point.visits), 1))
const maskIp = (ip) => { if (!ip) return 'Unknown'; if (ip.includes(':')) return `${ip.split(':').slice(0, 4).join(':')}:••••`; const parts = ip.split('.'); return parts.length === 4 ? `${parts[0]}.${parts[1]}.${parts[2]}.•••` : 'Masked' }
async function load() { loading.value = true; error.value = ''; try { analytics.value = (await adminApi.analytics(period.value)).data } catch (e) { error.value = e.message } finally { loading.value = false } }
onMounted(load)
</script>

<template>
  <section>
    <div class="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end">
      <div><p class="admin-eyebrow">Studio overview</p><h1 class="admin-title">Good morning, Raldin.</h1><p class="mt-2 max-w-xl text-gray-500">A clear view of what is live, what is changing, and how visitors find the work.</p></div>
      <div class="flex flex-wrap gap-2"><router-link to="/admin/works/new" class="admin-button-primary">+ Case study</router-link><router-link to="/admin/labs/new" class="admin-button-secondary">+ App Lab</router-link></div>
    </div>
    <div v-if="error" class="mb-6 flex items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><span>{{ error }}</span><button class="font-semibold" @click="load">Retry</button></div>
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-6">
      <div v-for="card in [{label:'Published works', value:count('works','published'), to:'/admin/works'},{label:'Published Apps Lab', value:count('labs','published'), to:'/admin/labs'},{label:'Drafts to review', value:count('works','draft')+count('labs','draft'), to:'/admin/works?status=draft'},{label:'Visits', value:analytics.summary?.visits || 0, to:'#'},{label:'Unique visitors', value:analytics.summary?.uniqueVisitors || 0, to:'#'},{label:'Page views', value:analytics.summary?.pageViews || 0, to:'#'}]" :key="card.label" class="relative overflow-hidden rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><div class="absolute right-0 top-0 h-20 w-20 rounded-full bg-[#BBE6F6]/50 blur-2xl" /><p class="relative text-xs font-bold uppercase tracking-[.12em] text-gray-500">{{ card.label }}</p><p class="relative mt-4 font-bricolage text-4xl font-bold">{{ loading ? '—' : card.value }}</p><router-link v-if="card.to !== '#'" :to="card.to" class="relative mt-4 inline-block text-sm font-semibold text-[#17A6E3]">View details →</router-link><span v-else class="relative mt-4 inline-block text-xs text-gray-400">{{ period }} period</span></div>
    </div>

    <div class="mt-8 grid gap-6 xl:grid-cols-[1.5fr_1fr]">
      <div class="rounded-2xl border border-gray-200 bg-white p-5 sm:p-7">
        <div class="flex flex-wrap items-center justify-between gap-3"><div><p class="admin-eyebrow">Analytics</p><h2 class="admin-section-title">Traffic overview</h2></div><select v-model="period" class="admin-input max-w-[130px] py-2 text-sm" @change="load"><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option></select></div>
        <div v-if="!analytics.series?.length" class="mt-8 grid min-h-[230px] place-items-center rounded-2xl bg-[radial-gradient(ellipse_at_center,#BBE6F6,#F7F8FA_68%)] text-center"><div><p class="font-bricolage text-2xl font-semibold text-[#132132]">No traffic yet</p><p class="mt-2 text-sm text-gray-500">Visitor events will appear here after the public site is visited.</p></div></div>
        <div v-else class="mt-8 flex h-[230px] items-end gap-2 rounded-2xl bg-[#F7F8FA] p-4 sm:gap-3"><div v-for="point in analytics.series" :key="point.date" class="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2" :title="`${point.date}: ${point.visits} visits`"><div class="w-full max-w-8 rounded-t-lg bg-[#17A6E3] transition-all group-hover:bg-[#132132]" :style="{ height: `${Math.max((point.visits / maxVisits) * 170, 5)}px` }"></div><span class="max-w-full truncate text-[9px] text-gray-400">{{ point.date.slice(5) }}</span></div></div>
      </div>
      <div class="rounded-2xl border border-gray-200 bg-white p-5 sm:p-7"><p class="admin-eyebrow">Acquisition</p><h2 class="admin-section-title">Top referrals</h2><div v-if="!analytics.referrals?.length" class="mt-6 rounded-xl bg-gray-50 p-5 text-sm text-gray-500">No referral data yet.</div><div v-else class="mt-5 space-y-4"><div v-for="referral in analytics.referrals" :key="referral.origin" class="flex items-center justify-between gap-3 text-sm"><span class="truncate">{{ referral.origin }}</span><strong>{{ referral.visits }}</strong></div></div><div class="mt-8 border-t pt-6"><p class="admin-eyebrow">Devices</p><div v-if="!analytics.devices?.length" class="mt-3 text-sm text-gray-500">No device data yet.</div><div v-else class="mt-3 flex flex-wrap gap-2"><span v-for="device in analytics.devices" :key="device.category" class="rounded-full bg-[#BBE6F6] px-3 py-1 text-xs text-[#132132]">{{ device.category }} · {{ device.visits }}</span></div></div></div>
    </div>

    <div class="mt-6 grid gap-6 xl:grid-cols-[1fr_1.5fr]">
      <div class="rounded-2xl border border-gray-200 bg-white p-5 sm:p-7"><p class="admin-eyebrow">Audience geography</p><h2 class="admin-section-title">Where visitors come from</h2><div v-if="!analytics.locations?.length" class="mt-6 rounded-xl bg-gray-50 p-5 text-sm text-gray-500">No location data yet.</div><div v-else class="mt-5 space-y-4"><div v-for="location in analytics.locations" :key="location.countryCode" class="flex items-center gap-3"><span class="grid size-9 place-items-center rounded-xl bg-[#BBE6F6] text-xs font-bold text-[#132132]">{{ location.countryCode || '—' }}</span><div class="min-w-0 flex-1"><div class="flex justify-between gap-3 text-sm"><span class="truncate">{{ location.country || 'Unknown' }}</span><strong>{{ location.visits }}</strong></div><div class="mt-2 h-1.5 overflow-hidden rounded-full bg-gray-100"><div class="h-full rounded-full bg-[#17A6E3]" :style="{ width: `${Math.min((location.visits / Math.max(analytics.summary.visits || 1, 1)) * 100, 100)}%` }"></div></div></div></div></div></div>
      <div class="rounded-2xl border border-gray-200 bg-white p-5 sm:p-7"><div class="flex items-center justify-between"><div><p class="admin-eyebrow">Visitor intelligence</p><h2 class="admin-section-title">Recent visitor groups</h2></div><span class="text-xs text-gray-400">IP masked</span></div><div v-if="!analytics.visitors?.length" class="mt-6 rounded-xl bg-gray-50 p-5 text-sm text-gray-500">No visitor data yet.</div><div v-else class="mt-5 overflow-x-auto"><table class="w-full min-w-[640px] text-left text-sm"><thead class="border-b text-xs uppercase tracking-wider text-gray-400"><tr><th class="pb-3">Visitor</th><th class="pb-3">Location</th><th class="pb-3">ISP</th><th class="pb-3">Visits</th></tr></thead><tbody><tr v-for="visitor in analytics.visitors" :key="visitor.ipHash || visitor.ipAddress" class="border-b border-gray-100 last:border-0"><td class="py-3 font-mono text-xs">{{ maskIp(visitor.ipAddress) }}</td><td class="py-3 text-gray-500">{{ [visitor.city, visitor.country].filter(Boolean).join(', ') || 'Unknown' }}</td><td class="max-w-[180px] truncate py-3 text-gray-500">{{ visitor.isp || 'Unknown' }}</td><td class="py-3 font-semibold text-[#17A6E3]">{{ visitor.visits }}</td></tr></tbody></table></div></div>
    </div>

    <div class="mt-6 rounded-2xl border border-gray-200 bg-white p-5 sm:p-7"><div class="flex items-center justify-between"><div><p class="admin-eyebrow">Top content</p><h2 class="admin-section-title">Most viewed</h2></div><router-link to="/admin/settings" class="text-sm font-semibold text-[#17A6E3]">View logs →</router-link></div><div v-if="!analytics.topContent?.length" class="mt-5 rounded-xl bg-gray-50 p-5 text-sm text-gray-500">No content views yet.</div><div v-else class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div v-for="item in analytics.topContent" :key="`${item.type}-${item.slug}`" class="rounded-xl border border-gray-100 p-4"><p class="text-xs uppercase tracking-wider text-gray-400">{{ item.type }}</p><p class="mt-2 truncate font-semibold">{{ item.slug }}</p><p class="mt-1 text-sm text-[#17A6E3]">{{ item.views }} views</p></div></div></div>
  </section>
</template>
